name: Valdidate terraform infrastructure

on:
  workflow_dispatch:

env:
  TARGET_DIR: infrastructure

jobs:
  test:
    runs-on: ubuntu-latest
    name: test infrastructure

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
      
      - name: Configure aws credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-east-1
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      
      - name: Terraform init
        run: |
          cd infrastructure 
          terraform init 

      - name: Check with tfsec
        uses: aquasecurity/tfsec-action@v1.0.0
        with:
          working_directory: ${{ env.TARGET_DIR }}
          soft_fail: true

      - name: Setup TFLint
        uses: terraform-linters/setup-tflint@v4

      - name: Init TFLint
        run: | 
          tflint --init --chdir=${{ env.TARGET_DIR }}
          tflint --chdir=${{ env.TARGET_DIR }} || true
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN_GIT }}

      - name: Terraform fmt
        run: |
          cd infrastructure 
          terraform fmt 
      
      - name: Terraform validate
        run: |
          cd infrastructure 
          terraform validate | true

      - name: Terraform plan
        run: |
          cd infrastructure 
          terraform plan