name: Test workflow for plan and apply

on:
  push:
  pull_request:

env:
  TARGET_DIR: infrastructure

jobs:
  test:
    runs-on: ubuntu-latest
    name: test infrastructure

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
      
      - name: Configure aws credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-east-1
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      
      - name: Terraform init
        run: terraform init --chdir=${{ env.TARGET_DIR }}

      - name: Check with tfsec
        uses: aquasecurity/tfsec-action@v1.0.0
        with:
          working_directory: ${{ env.TARGET_DIR }}

      - name: Setup TFLint
        uses: terraform-linters/setup-tflint@v4

      - name: Init TFLint
        run: | 
          tflint --init --chdir=${{ env.TARGET_DIR }}
          tflint --chdir=${{ env.TARGET_DIR }}
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN_GIT }}

      - name: Terraform fmt
        run: terraform fmt --chdir=${{ env.TARGET_DIR }}

      - name: Terraform plan
        run: terraform plan -out=tfplan -chdir=${{ env.TARGET_DIR }}

      - name: Terraform apply
        if: github.ref == 'refs/heads/main'
        run: terraform apply -chdir=${{ env.TARGET_DIR }} tfplan

        

      