name: Terraform apply (manual)

on:
  workflow_dispatch:

env:
  TARGET_DIR: infrastructure

jobs:
  apply:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-east-1
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          
      - name: Terraform init
        run: |
          cd infrastructure 
          terraform init 
          
      - name: Terraform destroy
        run: |
          cd infrastructure
          terraform destroy --auto-approve